import type { Formation, FormationKey, Position, SlotPosition } from "@/types/team";

const slot = (id: string, role: Position, x: number, y: number): SlotPosition => ({ id, role, x, y });

export const FORMATIONS: Record<FormationKey, Formation> = {
    "4-4-2": {
        key: "4-4-2",
        label: "4-4-2",
        slots: [
            slot("gk", "GK", 50, 92),
            slot("lb", "DEF", 12, 72),
            slot("lcb", "DEF", 36, 76),
            slot("rcb", "DEF", 64, 76),
            slot("rb", "DEF", 88, 72),
            slot("lm", "MID", 12, 48),
            slot("lcm", "MID", 38, 50),
            slot("rcm", "MID", 62, 50),
            slot("rm", "MID", 88, 48),
            slot("ls", "FWD", 38, 22),
            slot("rs", "FWD", 62, 22),
        ],
    },
    "4-3-3": {
        key: "4-3-3",
        label: "4-3-3",
        slots: [
            slot("gk", "GK", 50, 92),
            slot("lb", "DEF", 12, 72),
            slot("lcb", "DEF", 36, 76),
            slot("rcb", "DEF", 64, 76),
            slot("rb", "DEF", 88, 72),
            slot("cdm", "MID", 50, 58),
            slot("lcm", "MID", 28, 46),
            slot("rcm", "MID", 72, 46),
            slot("lw", "FWD", 14, 22),
            slot("st", "FWD", 50, 16),
            slot("rw", "FWD", 86, 22),
        ],
    },
    "4-2-3-1": {
        key: "4-2-3-1",
        label: "4-2-3-1",
        slots: [
            slot("gk", "GK", 50, 92),
            slot("lb", "DEF", 12, 72),
            slot("lcb", "DEF", 36, 76),
            slot("rcb", "DEF", 64, 76),
            slot("rb", "DEF", 88, 72),
            slot("ldm", "MID", 34, 58),
            slot("rdm", "MID", 66, 58),
            slot("lam", "MID", 18, 36),
            slot("cam", "MID", 50, 36),
            slot("ram", "MID", 82, 36),
            slot("st", "FWD", 50, 14),
        ],
    },
    "3-5-2": {
        key: "3-5-2",
        label: "3-5-2",
        slots: [
            slot("gk", "GK", 50, 92),
            slot("lcb", "DEF", 22, 76),
            slot("ccb", "DEF", 50, 78),
            slot("rcb", "DEF", 78, 76),
            slot("lwb", "MID", 8, 54),
            slot("ldm", "MID", 32, 56),
            slot("cdm", "MID", 50, 50),
            slot("rdm", "MID", 68, 56),
            slot("rwb", "MID", 92, 54),
            slot("ls", "FWD", 38, 20),
            slot("rs", "FWD", 62, 20),
        ],
    },
    "3-4-3": {
        key: "3-4-3",
        label: "3-4-3",
        slots: [
            slot("gk", "GK", 50, 92),
            slot("lcb", "DEF", 22, 76),
            slot("ccb", "DEF", 50, 78),
            slot("rcb", "DEF", 78, 76),
            slot("lm", "MID", 12, 50),
            slot("lcm", "MID", 38, 52),
            slot("rcm", "MID", 62, 52),
            slot("rm", "MID", 88, 50),
            slot("lw", "FWD", 18, 22),
            slot("st", "FWD", 50, 18),
            slot("rw", "FWD", 82, 22),
        ],
    },
    "5-3-2": {
        key: "5-3-2",
        label: "5-3-2",
        slots: [
            slot("gk", "GK", 50, 92),
            slot("lwb", "DEF", 8, 70),
            slot("lcb", "DEF", 30, 78),
            slot("ccb", "DEF", 50, 80),
            slot("rcb", "DEF", 70, 78),
            slot("rwb", "DEF", 92, 70),
            slot("lcm", "MID", 28, 48),
            slot("cm", "MID", 50, 48),
            slot("rcm", "MID", 72, 48),
            slot("ls", "FWD", 38, 20),
            slot("rs", "FWD", 62, 20),
        ],
    },
};

export const FORMATION_LIST: Formation[] = Object.values(FORMATIONS);
